from typing import Any

from engine.models.runtime import ActionResult, ExecutionContext

def click(params: dict[str, object], context: ExecutionContext) -> ActionResult: ...
def swipe(params: dict[str, object], context: ExecutionContext) -> ActionResult: ...
def long_click(params: dict[str, object], context: ExecutionContext) -> ActionResult: ...
def input_text(params: dict[str, object], context: ExecutionContext) -> ActionResult: ...
def key_press(params: dict[str, object], context: ExecutionContext) -> ActionResult: ...
def app_open(params: dict[str, object], context: ExecutionContext) -> ActionResult: ...
def app_stop(params: dict[str, object], context: ExecutionContext) -> ActionResult: ...
def screenshot(params: dict[str, object], context: ExecutionContext) -> ActionResult: ...
def exec_command(params: dict[str, object], context: ExecutionContext) -> ActionResult: ...
def create_selector(params: dict[str, object], context: ExecutionContext) -> ActionResult: ...
def dumpNodeXml(params: dict[str, object], context: ExecutionContext) -> ActionResult: ...
def dump_node_xml_ex(params: dict[str, object], context: ExecutionContext) -> ActionResult: ...

class MytSelector:
    rpc: Any
    selector: Any
    def addQuery_Text(self, value: str) -> bool: ...
    def addQuery_TextContain(self, value: str) -> bool: ...
    def addQuery_TextContainWith(self, value: str) -> bool: ...
    def addQuery_Clickable(self, clickable: bool = ...) -> bool: ...
    def addQuery_Id(self, value: str) -> bool: ...
    def addQuery_Class(self, value: str) -> bool: ...
    def addQuery_Desc(self, value: str) -> bool: ...
    def addQuery_Package(self, value: str) -> bool: ...
    def addQuery_Bounds(self, left: int, top: int, right: int, bottom: int) -> bool: ...
    def execQueryOne(self) -> ActionResult: ...
    def execQueryAll(self) -> ActionResult: ...

class RpcNode:
    node: Any
    def get_node_text(self) -> str: ...
    def get_node_id(self) -> str: ...
    def get_node_class(self) -> str: ...
    def get_node_package(self) -> str: ...
    def get_node_desc(self) -> str: ...
    def get_node_bound(self) -> dict[str, int]: ...
    def get_node_bound_center(self) -> dict[str, int]: ...
    def get_node_parent(self) -> Any: ...
    def get_node_child(self, index: int) -> Any: ...
    def get_node_child_count(self) -> int: ...
    def click_events(self) -> bool: ...
