from typing import Any, Dict, Mapping

class BaseHTTPClient:
    host: str
    port: int
    timeout_seconds: float
    retries: int
    def __init__(self, host: str, port: int, timeout_seconds: float = ..., retries: int = ...) -> None: ...
    def get(self, path: str, query: Mapping[str, Any] | None = ...) -> Dict[str, Any]: ...
    def post(self, path: str, payload: Mapping[str, Any] | None = ...) -> Dict[str, Any]: ...

class MytSdkClient:
    def __init__(self, device_ip: str, sdk_port: int = ..., timeout_seconds: float = ..., retries: int = ...) -> None: ...
    def get_device_info(self) -> Dict[str, Any]: ...
    def get_api_version(self) -> Dict[str, Any]: ...
    def start_android(self, name: str, **kwargs: Any) -> Dict[str, Any]: ...
    def stop_android(self, name: str) -> Dict[str, Any]: ...
    def restart_android(self, name: str) -> Dict[str, Any]: ...
    def rename_android(self, old_name: str, new_name: str) -> Dict[str, Any]: ...
    def exec_android(self, name: str, command: str) -> Dict[str, Any]: ...
    def get_cloud_status(self, name: str) -> Dict[str, Any]: ...
    def switch_image(self, name: str, image_url: str, **kwargs: Any) -> Dict[str, Any]: ...
    def switch_model(self, name: str, model_id: str, **kwargs: Any) -> Dict[str, Any]: ...
    def pull_image(self, image_url: str) -> Dict[str, Any]: ...
    def list_images(self) -> Dict[str, Any]: ...
    def prune_images(self) -> Dict[str, Any]: ...
